@startuml
Title **TOSCA Implementation Landscape**
package "**Open Standards**" as Open_Standards {
  map "**ETSI GS NFV-SOL 001**" as ETSI_GS_NFV_SOL_001 #PaleGreen {
    TOSCA => 1.1 + 1.2 + 1.3
    Target => NFV
    Links => [[https://www.etsi.org/deliver/etsi_gs/NFV-SOL/001_099/001/03.05.01_60/gs_NFV-SOL001v030501p.pdf <img:icons/Spec.png{scale=0.5}>]] [[https://forge.etsi.org/rep/nfv/SOL001 <img:icons/Forge.png{scale=0.5}>]]
  }
  map "**TM Forum IG1176**" as TM_Forum_IG1176 #PaleGreen {
    TOSCA => 1.3
    Target => Model-Driven Automation
    Links => [[https://www.tmforum.org/resources/standard/ig1176-tosca-guide-for-model-driven-automation-v4-1-0 <img:icons/Spec.png{scale=0.5}>]] [[https://github.com/pmjordan/TOSCA_for_TMForum <img:icons/GitHub.png{scale=0.5}>]]
  }
}
package "**EU Funded Projects**" as EU_Funded_Projects {
  map "**CELAR**" as CELAR #DarkRed {
    Links => [[https://github.com/CELAR <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**DICE**" as DICE #DarkRed {
    Links => [[https://github.com/dice-project <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**INDIGO - DataCloud**" as INDIGO___DataCloud #PaleGreen {
    Links => [[https://www.indigo-datacloud.eu <img:icons/Website.png{scale=0.5}>]] [[https://github.com/indigo-dc <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**SeaClouds**" as SeaClouds #DarkRed {
    Links => [[http://www.seaclouds-project.eu <img:icons/Website.png{scale=0.5}>]] [[https://github.com/SeaCloudsEU <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**Radon**" as Radon #PaleGreen {
    Links => [[https://radon-h2020.eu <img:icons/Website.png{scale=0.5}>]] [[https://github.com/radon-h2020 <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**Sodalite**" as Sodalite #PaleGreen {
    Links => [[https://www.sodalite.eu <img:icons/Website.png{scale=0.5}>]] [[https://github.com/SODALITE-EU <img:icons/GitHub.png{scale=0.5}>]]
  }
}
package "**Open Source Communities**" as Open_Source_Communities {
  map "**OpenStack**" as OpenStack #PaleGreen {
    Links => [[https://www.openstack.org <img:icons/Website.png{scale=0.5}>]] [[https://github.com/openstack <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**ONAP**" as ONAP #PaleGreen {
    Links => [[https://www.onap.org <img:icons/Website.png{scale=0.5}>]] [[https://github.com/onap <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**Open Baton**" as Open_Baton #PaleGreen {
    Links => [[https://openbaton.github.io <img:icons/Website.png{scale=0.5}>]] [[https://github.com/openbaton <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**OPNFV**" as OPNFV #PaleGreen {
    Links => [[https://www.opnfv.org <img:icons/Website.png{scale=0.5}>]]
  }
}
package "**TOSCA Modeling Tools**" as TOSCA_Modeling_Tools {
  map "**Alien4Cloud**" as Alien4Cloud #PaleGreen {
    TOSCA => 1.0 + Alien DSL
    Target => Any cloud
    Usage => Webapp
    Nature => Open source
    Language => Java
    Links => [[http://alien4cloud.github.io <img:icons/Website.png{scale=0.5}>]] [[https://github.com/alien4cloud <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**Cloud Topology Designer**" as Cloud_Topology_Designer #PaleGreen {
    TOSCA => 1.0 + Alien DSL
    Target => Open Telekom Cloud
    Usage => SaaS
    Nature => Commercial product
    Links => [[https://designer.otc-service.com <img:icons/SaaS.png{scale=0.5}>]]
  }
  map "**c-Eclipse**" as c_Eclipse #DarkRed {
    TOSCA => Unknown
    Usage => <img:icons/Eclipse.png{scale=0.5}>
    Nature => Open source
    Language => Java
    Links => [[https://github.com/CELAR/c-Eclipse <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**DICER**" as DICER #DarkRed {
    TOSCA => Cloudify DSL
    Usage => <img:icons/Eclipse.png{scale=0.5}>
    Nature => Open source
    Language => Java
    Links => [[https://github.com/dice-project/DICER <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**Eclipse Winery**" as Eclipse_Winery #PaleGreen {
    TOSCA => XML + 1.3
    Usage => Webapp + <img:icons/Eclipse.png{scale=0.5}>
    Nature => Academia product\nOpen source
    Language => Java
    Links => [[https://projects.eclipse.org/projects/soa.winery <img:icons/Website.png{scale=0.5}>]] [[https://github.com/eclipse/winery <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**EnterpriseWeb**" as EnterpriseWeb #White {
    TOSCA => Unknown
    Usage => Unknown
    Nature => Commercial product
    Links => [[https://enterpriseweb.com <img:icons/Website.png{scale=0.5}>]]
  }
  map "**RADON IDE**" as RADON_IDE #PaleGreen {
    TOSCA => 1.3
    Usage => Webapp
    Nature => Open source
    Language => Java
    Links => [[https://github.com/radon-h2020/radon-ide <img:icons/GitHub.png{scale=0.5}>]]
  }
}
package "**TOSCA Marketplaces**" as TOSCA_Marketplaces {
  map "**xOpera Template Library**" as xOpera_Template_Library #PaleGreen {
    TOSCA => Any
    Usage => SaaS
    Nature => XLAB property
    Links => [[https://template-library-xopera.xlab.si <img:icons/SaaS.png{scale=0.5}>]]
  }
}
package "**TOSCA Orchestrators**" as TOSCA_Orchestrators {
  map "**Cisco NSO**" as Cisco_NSO #White {
    TOSCA => Unknown
    Target => Unknown
    Usage => Unknown
    Nature => Commercial product
    Links => [[https://www.cisco.com/c/en/us/products/cloud-systems-management/network-services-orchestrator/index.html <img:icons/Website.png{scale=0.5}>]]
  }
  map "**CPLANE.ai**" as CPLANE_ai #White {
    TOSCA => Unknown
    Target => Unknown
    Usage => Unknown
    Nature => Commercial product
    Links => [[https://cplaneai.com <img:icons/Website.png{scale=0.5}>]]
  }
  map "**Itential**" as Itential #White {
    TOSCA => Unknown
    Target => Unknown
    Usage => Unknown
    Nature => Commercial product
    Links => [[https://www.itential.com/products/automation-platform <img:icons/Website.png{scale=0.5}>]]
  }
  map "**Ubicity Orchestrator**" as Ubicity_Orchestrator #PaleGreen {
    TOSCA => 1.3 + 2.0
    Target => Any cloud
    Usage => CLI
    Nature => Commercial product
    Links => [[https://ubicity.com/products.html <img:icons/Website.png{scale=0.5}>]]
  }
  map "**Yorc**" as Yorc #PaleGreen {
    TOSCA => 1.2
    Target => Any cloud
    Usage => CLI
    Nature => Open source
    Language => Go
    Links => [[https://ystia.github.io <img:icons/Website.png{scale=0.5}>]] [[https://github.com/ystia/yorc <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**Cloudify**" as Cloudify #PaleGreen {
    TOSCA => Cloudify DSL
    Target => Any cloud
    Usage => CLI
    Nature => Commercial product\nOpen source
    Language => Python
    Links => [[https://cloudify.co <img:icons/Website.png{scale=0.5}>]] [[https://github.com/cloudify-cosmo <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**MSO4SC HPC**" as MSO4SC_HPC #Orange {
    TOSCA => Cloudify DSL
    Usage => Library
    Nature => Open source
    Language => Python
    Links => [[https://github.com/MSO4SC/cloudify-hpc-plugin <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**AriaTosca**" as AriaTosca #DarkRed {
    TOSCA => 1.0
    Target => Any cloud
    Usage => CLI
    Nature => Open source
    Language => Python
    Links => [[http://incubator.apache.org/projects/ariatosca.html <img:icons/Website.png{scale=0.5}>]] [[https://github.com/apache/incubator-ariatosca <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**INDIGO PaaS Orchestrator**" as INDIGO_PaaS_Orchestrator #PaleGreen {
    TOSCA => 1.0 + NFV 1.0
    Target => Any cloud
    Usage => Webapp
    Nature => Open source
    Language => Java
    Links => [[https://github.com/indigo-dc/orchestrator <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**TORCH**" as TORCH #Orange {
    TOSCA => 1.0
    Target => OpenStack + Azure +\nKubernetes + Docker Swarm
    Usage => Webapp
    Nature => Academia prototype\nOpen source
    Language => Java + JavaScript + Php + Python
    Links => [[https://github.com/unict-cclab/TORCH <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**Turandot**" as Turandot #PaleGreen {
    TOSCA => 1.3
    Target => Kubernetes
    Usage => CLI
    Nature => Open source
    Language => Go
    Links => [[https://turandot.puccini.cloud <img:icons/Website.png{scale=0.5}>]] [[https://github.com/tliron/turandot <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**Khutulun**" as Khutulun #PaleGreen {
    TOSCA => 2.0
    Target => Bare processes + Podman +\nsystemd-nspawn +\nDistrobox + libvirt + Firewalld
    Usage => CLI + Webapp
    Nature => Open source
    Language => Go
    Links => [[https://khutulun.puccini.cloud <img:icons/Website.png{scale=0.5}>]] [[https://github.com/tliron/khutulun <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**Unfurl**" as Unfurl #PaleGreen {
    TOSCA => 1.3 + Unfurl DSL
    Target => Any cloud
    Usage => CLI
    Nature => Open source
    Language => Python
    Links => [[https://unfurl.run <img:icons/Website.png{scale=0.5}>]] [[https://github.com/onecommons/unfurl <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**OpenTOSCA**" as OpenTOSCA #PaleGreen {
    TOSCA => 1.3
    Target => Any cloud
    Usage => Webapp
    Nature => Academia product\nOpen source
    Language => Java
    Links => [[https://www.opentosca.org <img:icons/Website.png{scale=0.5}>]] [[https://github.com/OpenTOSCA <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**TosKer**" as TosKer #DarkRed {
    TOSCA => 1.0
    Target => Docker
    Usage => CLI
    Nature => Academia prototype\nOpen source
    Language => Python
    Links => [[https://github.com/di-unipi-socc/tosker <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**xOpera Opera**" as xOpera_Opera #PaleGreen {
    TOSCA => 1.3
    Target => Any cloud
    Usage => CLI
    Nature => Open source
    Language => Python
    Links => [[https://github.com/xlab-si/xopera-opera <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**xOpera SaaS**" as xOpera_SaaS #PaleGreen {
    TOSCA => 1.3
    Target => Any cloud
    Usage => SaaS
    Nature => XLAB property
    Links => [[https://saas-xopera.xlab.si <img:icons/SaaS.png{scale=0.5}>]]
  }
  map "**Tacker**" as Tacker #PaleGreen {
    TOSCA => 1.1 + NFV 1.0
    Target => OpenStack
    Usage => CLI
    Nature => Open source
    Language => Python
    Links => [[https://wiki.openstack.org/wiki/Tacker <img:icons/Website.png{scale=0.5}>]] [[https://github.com/openstack/tacker <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**MiCADOscale**" as MiCADOscale #PaleGreen {
    TOSCA => 1.0 + 1.2 + 1.3
    Target => Any cloud + Kubernetes
    Usage => CLI
    Nature => Academia prototype\nOpen source
    Language => Python
    Links => [[https://micado-scale.eu/ <img:icons/Website.png{scale=0.5}>]] [[https://micado-scale.readthedocs.io Doc]] [[https://github.com/micado-scale <img:icons/GitHub.png{scale=0.5}>]]
  }
}
package "**TOSCA Developer Tools**" as TOSCA_Developer_Tools {
  map "**Cloudnet TOSCA Toolbox**" as Cloudnet_TOSCA_Toolbox #PaleGreen {
    TOSCA => 1.0 + 1.1 + 1.2 + 1.3 + 2.0
    Usage => CLI
    Nature => Academia product\nOpen source
    Language => Python
    Links => [[https://github.com/Orange-OpenSource/Cloudnet-TOSCA-toolbox <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**TOSCA toolbox**" as TOSCA_toolbox #PaleGreen {
    TOSCA => 1.0 + 1.1 + 1.2 + 1.3 + 2.0
    Usage => SaaS
    Nature => Orange property
    Links => [[https://toscatoolbox.orange.com <img:icons/SaaS.png{scale=0.5}>]]
  }
  map "**Heat-Translator**" as Heat_Translator #PaleGreen {
    TOSCA => 1.0
    Target => OpenStack
    Usage => CLI
    Nature => Open source
    Language => Python
    Links => [[https://wiki.openstack.org/wiki/Heat-Translator <img:icons/Website.png{scale=0.5}>]] [[https://github.com/openstack/heat-translator <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**TosKeriser**" as TosKeriser #Orange {
    TOSCA => 1.0
    Target => Docker
    Usage => CLI
    Nature => Academia prototype\nOpen source
    Language => Python
    Links => [[https://github.com/di-unipi-socc/TosKeriser <img:icons/GitHub.png{scale=0.5}>]]
  }
  package "**TOSCA Parsers**" as TOSCA_Parsers {
    map "**JTOSCA parser**" as JTOSCA_parser #Orange {
      TOSCA => 1.0
      Usage => Library
      Nature => Open source
      Language => Java
      Links => [[https://github.com/onap/sdc-jtosca <img:icons/GitHub.png{scale=0.5}>]]
    }
    map "**Puccini**" as Puccini #PaleGreen {
      TOSCA => 1.0 + 1.1 + 1.2 + 1.3 + 2.0 +\nCloudify DSL + OpenStack Heat
      Usage => CLI + Webapp
      Nature => Open source
      Language => Go
      Links => [[https://puccini.cloud <img:icons/Website.png{scale=0.5}>]] [[https://github.com/tliron/puccini <img:icons/GitHub.png{scale=0.5}>]]
    }
    map "**Sommelier**" as Sommelier #Orange {
      TOSCA => 1.0
      Usage => CLI
      Nature => Academia prototype\nOpen source
      Language => Python
      Links => [[https://github.com/di-unipi-socc/Sommelier <img:icons/GitHub.png{scale=0.5}>]]
    }
    map "**tosca-parser**" as tosca_parser #PaleGreen {
      TOSCA => 1.0 + NFV 1.0 + 1.1 + 1.2
      Usage => CLI
      Nature => Open source
      Language => Python
      Links => [[https://wiki.openstack.org/wiki/TOSCA-Parser <img:icons/Website.png{scale=0.5}>]] [[https://github.com/openstack/tosca-parser <img:icons/GitHub.png{scale=0.5}>]]
    }
  }
  map "**oas2tosca**" as oas2tosca #PaleGreen {
    TOSCA => 1.3
    Usage => CLI
    Nature => Open source
    Language => Python
    Links => [[https://github.com/lauwers/oas2tosca <img:icons/GitHub.png{scale=0.5}>]]
  }
  map "**yang2tosca**" as yang2tosca #PaleGreen {
    TOSCA => 1.3
    Usage => CLI
    Nature => Open source
    Language => Python
    Links => [[https://github.com/lauwers/yang2tosca <img:icons/GitHub.png{scale=0.5}>]]
  }
}
CELAR o-- c_Eclipse : <<contributes>>
DICE o-- DICER : <<contributes>>
INDIGO___DataCloud *-up- INDIGO_PaaS_Orchestrator : <<hosts>>
SeaClouds ..> Alien4Cloud : <<uses>>
Radon o-- RADON_IDE : <<contributes>>
Radon o-- OpenTOSCA : <<contributes>>
Sodalite ..> xOpera_Opera : <<uses>>
OpenStack *-up- tosca_parser : <<hosts>>
OpenStack *-up- Heat_Translator : <<hosts>>
OpenStack *-up- Tacker : <<hosts>>
ONAP *-up- JTOSCA_parser : <<hosts>>
Alien4Cloud ..> Yorc : <<uses>>
Alien4Cloud ..> Cloudify : <<uses>>
Cloud_Topology_Designer ..> Alien4Cloud : <<uses>>
DICER ..> Cloudify : <<uses>>
Eclipse_Winery -- OpenTOSCA : <<same ecosystem>>
RADON_IDE ..> Eclipse_Winery : <<uses>>
RADON_IDE ..> xOpera_SaaS : <<uses>>
RADON_IDE ..> xOpera_Template_Library : <<uses>>
Cloudify <.. MSO4SC_HPC : <<plugins>>
TORCH ..> tosca_parser : <<uses>>
Turandot ..> Puccini : <<uses>>
Khutulun ..> Puccini : <<uses>>
Unfurl ..> tosca_parser : <<uses>>
TosKer -- Sommelier : <<same ecosystem>>
TosKer -- TosKeriser : <<same ecosystem>>
xOpera_SaaS ..> xOpera_Opera : <<uses>>
Tacker ..> tosca_parser : <<uses>>
MiCADOscale ..> tosca_parser : <<uses>>
Cloudnet_TOSCA_Toolbox ..up..> AriaTosca : <<applied to>>
Cloudnet_TOSCA_Toolbox ..up..> ETSI_GS_NFV_SOL_001 : <<applied to>>
Cloudnet_TOSCA_Toolbox ..up..> Khutulun : <<applied to>>
Cloudnet_TOSCA_Toolbox ..up..> TORCH : <<applied to>>
Cloudnet_TOSCA_Toolbox ..up..> TosKer : <<applied to>>
Cloudnet_TOSCA_Toolbox ..up..> xOpera_Opera : <<applied to>>
TOSCA_toolbox ..> Cloudnet_TOSCA_Toolbox : <<uses>>
Heat_Translator ..> tosca_parser : <<uses>>
TosKeriser -- Sommelier : <<same ecosystem>>
Sommelier ..> tosca_parser : <<uses>>
oas2tosca -- yang2tosca : <<same ecosystem>>
yang2tosca -- oas2tosca : <<same ecosystem>>
TOSCA_toolbox .up[hidden]. Cloudnet_TOSCA_Toolbox
Heat_Translator .up[hidden]. tosca_parser
Heat_Translator .up[hidden]. tosca_parser
Open_Standards --[hidden]-- EU_Funded_Projects
EU_Funded_Projects --[hidden]-- TOSCA_Modeling_Tools
TOSCA_Modeling_Tools --[hidden]-- TOSCA_Marketplaces
TOSCA_Marketplaces --[hidden]-- TOSCA_Orchestrators
TOSCA_Orchestrators --[hidden]-- TOSCA_Developer_Tools
TOSCA_Developer_Tools --[hidden]-- Open_Source_Communities
@enduml
